  name: Bug Report
  description: Report a bug or issue
  title: "[Bug]: "
  labels: ["Bug"]
  body:
    - type: markdown
      attributes:
        value: |
          Thanks for reporting a bug! Please provide as much detail as possible.

    - type: textarea
      id: description
      attributes:
        label: Bug Description
        description: What happened?
        placeholder: Describe the bug...
      validations:
        required: true

    - type: textarea
      id: reproduce
      attributes:
        label: Steps to Reproduce
        description: How can we reproduce this issue?
        placeholder: |
          1. Go to...
          2. Click on...
          3. See error...
      validations:
        required: true

    - type: textarea
      id: expected
      attributes:
        label: Expected Behavior
        description: What should happen instead?
      validations:
        required: true

    - type: textarea
      id: actual
      attributes:
        label: Actual Behavior
        description: What actually happened?
      validations:
        required: true

    - type: dropdown
      id: version
      attributes:
        label: Version
        description: Which version are you using?
        options:
          - Latest (stable)
          - Beta/Dev
          - Older version
      validations:
        required: true

    - type: dropdown
      id: platform
      attributes:
        label: Platform
        description: What platform are you on?
        options:
          - Windows
          - macOS
          - Linux
          - Web Browser
          - Other
      validations:
        required: true

    - type: textarea
      id: logs
      attributes:
        label: Logs/Screenshots
        description: Add any relevant logs or screenshots
        placeholder: Paste logs or drag images here...