  name: Feature Request
  description: Suggest a new feature or improvement
  title: "[Feature]: "
  labels: ["Feature Request"]
  body:
    - type: markdown
      attributes:
        value: |
          Thanks for taking the time to suggest a feature! We aren't afraid to add features that should not be locked behind a paywall!

    - type: textarea
      id: description
      attributes:
        label: Feature Description
        description: What feature would you like to see?
        placeholder: Describe the feature you'd like...
      validations:
        required: true

    - type: textarea
      id: usecase
      attributes:
        label: Use Case
        description: Why would this feature be useful?
        placeholder: Explain how this would improve your experience...
      validations:
        required: true

    - type: textarea
      id: alternatives
      attributes:
        label: Alternatives Considered
        description: Have you considered any alternative solutions?
        placeholder: Any workarounds or alternative approaches?
      validations:
        required: false

    - type: dropdown
      id: platform
      attributes:
        label: Platform
        description: Which platform is this for?
        options:
          - CatRealm Client
          - CatRealm Server
          - Both
          - Other
      validations:
        required: true